import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoExpo",
  description: "Generated by lee",
};

// app/layout.tsx

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal?: React.ReactNode; //  optional
}) {
  return (
    <html>
      <body>
        <Navbar />
        <main>
          {children}
          {modal}
        </main>
        {/* Vercel Analytics 추가 */}
        <Analytics />
      </body>
    </html>
  );
}
